site_name: Zarr Cloud-Native Workflow for Water Body Detection

theme:
    logo: imgs/icon-eoap.png
    name: material

    palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
plugins:
  - search
  - mermaid2:
      version: 10.6.0
  - mkdocs-jupyter:
      execute: true
      show_input: True
      no_input: False

markdown_extensions:
  - pymdownx.details
  - abbr
  - admonition
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - attr_list
  - pymdownx.snippets:
      base_path: './'
  - pymdownx.highlight:
      line_spans: __span
extra_css:
  - styles/css/app.css
  
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  

nav:
  - Introduction: 'index.md'
  - Design:
    - water-bodies: 'design/water-bodies.md'
  - On-boarding:
    - Developers: 'on-boarding/developers.md'
    - EOAP Users: 'on-boarding/eoap-users.md'
    - Maintainers: 'on-boarding/maintainers.md'
  - Producer Outputs Contract: 'producer-outputs.md'
  - How-to:
    - stac-zarr Usage: 'how-to/stac-zarr-usage.md'
    - Produced STAC Objects: 'how-to/stac-produced-objects.md'
    - TiTiler-EOPF + Collection: 'how-to/titiler-eopf-collection.md'
    - TiTiler-EOPF + Item: 'how-to/titiler-eopf-item.md'
    - TiTiler-EOPF HTML Client: 'how-to/titiler-eopf-html-client.md'
    - TiTiler-EOPF Patch: 'how-to/titiler-eopf-patch.md'
  - Compliance:
    - GeoZarr Minispec Compliance: 'compliance/geozarr-minispec-compliance.md'
    - STAC Zarr Best Practices: 'compliance/stac-zarr-best-practices.md'
  - Input STAC Requirements: 'input-stac.md'
  - TL;DR: exploitation.ipynb
  - CWL CommandLineTools:
    - discovery: 'cwl-cli/discovery.ipynb'
    - convert-search: 'cwl-cli/convert-search.ipynb'
    - stac-collection: 'cwl-cli/stac-collection.ipynb'
    - stac-zarr: 'cwl-cli/stac-zarr.ipynb'
  - CWL Sub-workflows:
    - water-bodies-detection: 'sub-workflow/water-bodies-detection.ipynb'
  - CWL Workflows:
     - producer: 'cwl-workflows/producer.ipynb'
     - consumer: 'cwl-workflows/consumer.ipynb'
  - Practice Labs: labs.md

copyright: <a href="https://img.shields.io/badge/License-CC_BY--SA_4.0-lightgrey.svg">License CC BY-SA 4.0</a>, by <a href="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons</a>
